# Generated by Django 5.1.1 on 2024-10-24 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id_doctor', models.AutoField(primary_key=True, serialize=False)),
                ('name_doctor', models.CharField(max_length=255)),
                ('email_doctor', models.EmailField(max_length=255, unique=True)),
                ('colegiatura_doctor', models.CharField(max_length=255)),
                ('password_doctor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_patient', models.AutoField(primary_key=True, serialize=False)),
                ('name_patient', models.CharField(max_length=255)),
                ('dni_patient', models.IntegerField(unique=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Radiograph',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_radiograph', models.DateField()),
                ('image_radiograph', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detection_radiograph', models.CharField(max_length=255)),
                ('prediction_radiograph', models.CharField(max_length=255)),
                ('radiograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.radiograph')),
            ],
        ),
    ]
