# Generated by Django 5.1.1 on 2024-09-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id_doctor', models.AutoField(primary_key=True, serialize=False)),
                ('name_doctor', models.CharField(max_length=255)),
                ('email_doctor', models.EmailField(max_length=255, unique=True)),
                ('colegiatura_doctor', models.CharField(max_length=255)),
                ('password_doctor', models.CharField(max_length=255)),
            ],
        ),
    ]
