# Generated by Django 5.1.1 on 2024-10-24 17:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_radiograph_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='heat_image_radiograph',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='id_analysis',
        ),
        migrations.RemoveField(
            model_name='radiograph',
            name='id_radiograph',
        ),
        migrations.AddField(
            model_name='analysis',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radiograph',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysis',
            name='detection_radiograph',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='prediction_radiograph',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='radiograph',
            name='image_radiograph',
            field=models.CharField(max_length=255),
        ),
    ]
